version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: riftvision-postgres
    restart: always
    environment:
      POSTGRES_DB: riftvision
      POSTGRES_USER: riftvision
      POSTGRES_PASSWORD: riftvision
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/datamu

volumes:
  postgres_data: