spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riftvision
    username: riftvision
    password: riftvision

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: 01234567890123456789012345678901
  expiration: 3600000