spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/riftvision
    username: riftvision
    password: riftvision

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

riot:
  api-key: ${RIOT_API_KEY}
  account-base-url: https://europe.api.riotgames.com
  match-base-url: https://europe.api.riotgames.com